// 测试SLS风格UI功能
console.log('🎯 测试SLS风格错误日志UI...')

console.log('✨ SLS风格UI特性:')
console.log('✅ 搜索和过滤功能')
console.log('   - 支持按错误类型、消息、页面搜索')
console.log('   - 支持按严重程度过滤')
console.log('   - 实时搜索响应')

console.log('✅ 多字段排序')
console.log('   - 按时间排序 (最新/最旧)')
console.log('   - 按发生次数排序')
console.log('   - 按严重程度排序')
console.log('   - 支持升序/降序切换')

console.log('✅ 分页显示')
console.log('   - 每页显示20条记录')
console.log('   - 显示总记录数')
console.log('   - 上一页/下一页导航')

console.log('✅ 详细的错误信息展示')
console.log('   - 错误类型和消息')
console.log('   - 发生次数和最后发生时间')
console.log('   - 页面路径和来源')
console.log('   - 用户代理和IP地址')
console.log('   - 追踪ID (Trace ID)')

console.log('✅ 类似阿里云SLS的UI风格')
console.log('   - 专业的日志查询界面')
console.log('   - 清晰的错误级别标识')
console.log('   - 结构化的信息展示')
console.log('   - 悬停效果和交互反馈')

console.log('✅ 热力图视图')
console.log('   - 基于严重程度的颜色编码')
console.log('   - 基于发生次数的大小变化')
console.log('   - 悬停显示详细信息')

console.log('\n🎉 SLS风格UI测试完成!')
console.log('💡 现在可以访问 http://localhost:3001/zh/dashboard 体验:')
console.log('   1. 点击"前端错误日志"卡片右上角的切换按钮')
console.log('   2. 在SLS列表视图和热力图视图之间切换')
console.log('   3. 使用搜索框搜索特定错误')
console.log('   4. 使用过滤下拉菜单按严重程度过滤')
console.log('   5. 点击排序按钮按不同字段排序')
console.log('   6. 点击错误日志条目查看详细信息')

console.log('\n🔍 演示数据包含:')
console.log('   - 5个不同类型的错误')
console.log('   - 不同的严重程度 (高/中/低)')
console.log('   - 不同的发生次数 (1-8次)')
console.log('   - 不同的页面路径')
console.log('   - 完整的错误信息和堆栈跟踪')
